<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8CAR6C7" failures="1" tests="1" name="runners.ExcessFundRunner" time="13.100" errors="0" timestamp="2025-03-18T12:25:35 IST" skipped="0">
  <testcase classname="runners.ExcessFundRunner" name="runScenario" time="13.100">
    <failure message="Error message mismatch! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at stepDefinitions.ExcessFundSteps.user_should_see_the_error_message_excess(ExcessFundSteps.java:81)
at âœ½.User should see the error message "Insufficient funds" for excess fund transfer(file:///C:/Users/dpraj/Downloads/Zero_Bank/Zero_Bank/Zero_Capston_Project/src/test/resources/features/ExcessFund.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runners.ExcessFundRunner -->
